<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/10/11
 * Time: 14:20
 */

namespace app\seller\controller;

use EasyWeChat\Foundation\Application;
use EasyWeChat\Payment\Order;
use think\AjaxPage;
use think\Page;
use think\Db;

class Redpacket extends Base
{
    public $config;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        date_default_timezone_set("Asia/chongqing");
        error_reporting(E_ERROR);
        header("Content-Type: text/html; charset=utf-8");
        $this->config=json_decode(preg_replace("/\/\*[\s\S]+?\*\//", "", file_get_contents("public/config.json")),true);
    }


    //红包

    /*
     * 红包列表
     */
    public function index()
    {
        //获取优惠券列表
        $count = M('red_packet')->where("store_id", STORE_ID)->count();
        $Page = new Page($count, 10);
        $show = $Page->show();
        $lists = M('red_packet')->where("store_id", STORE_ID)->order('send_start_time desc')->limit($Page->firstRow . ',' . $Page->listRows)->select();
        $this->assign('lists', $lists);
        $this->assign('page', $show);// 赋值分页输出
        $this->assign('redpacket', C('RED_PACKET_TYPE'));
        return $this->fetch();
    }

    public function send_redpacket()
    {

        return $this->fetch();
    }


    /*
     * 添加指定人红包
     */
    public function redpacket_info()
    {
        if (IS_POST) {
            $data = I('post.');
            $data['send_start_time'] = strtotime($data['send_start_time']);
            $data['send_end_time'] = strtotime($data['send_end_time']);
            if (empty($data['name'])) {
                $this->error('红包名称不能为空', null, null, 1);
            }
            if (empty($data['one_money'])) {
                $this->error('红包发放金额不能为空', null, null, 1);
            }
            if (empty($data['type'])) {
                $this->error('请选择发放类型', null, null, 1);
            }
            if (empty($data['createnum'])) {
                $this->error('红包数量不能为空', null, null, 1);
            }
            if (empty($data['id'])) {
                $data['store_id'] = STORE_ID;
                $row = M('red_packet')->add($data);
            } else {
                $row = M('red_packet')->where(array('id' => $data['id'], 'store_id' => STORE_ID))->save($data);
            }
            if (!$row) {
                $this->error('添加 / 编辑红包失败');
            }
            $this->success('添加 / 编辑红包成功', U('Redpacket/index'));
            exit;
        }
        $cid = I('get.id/d');
        if ($cid) {
            $redPacket = M('red_packet')->where(array('id' => $cid, 'store_id' => STORE_ID))->find();
            if (empty($redPacket)) {
                $this->error('红包不存在');
            }
            $this->assign('redpacket', $redPacket);
        } else {
            $def['send_start_time'] = time();
            $def['send_end_time'] = strtotime("+1 month");
            $this->assign('redpacket', $def);
        }
        return $this->fetch();
    }

    /*
 * 添加所有人红包
 */
    public function redpacket_all_info()
    {
        if (IS_POST) {
            Db::startTrans();
            $data = I('post.');
            $data['send_start_time'] = strtotime($data['send_start_time']);
            $data['send_end_time'] = strtotime($data['send_end_time']);
            if (empty($data['goods_name'])) {
                $this->error('商品名称不能为空', null, null, 1);
            }
            if (empty($data['shop_price'])) {
                $this->error('本店售价不能为空', null, null, 1);
            }
            if (empty($data['problem'])) {
                $this->error('请填写问题,必须关于上面描述有关');
            }
            if (empty($data['A']) || empty($data['B']) || empty($data['C']) || empty($data['D'])) {
                $this->error('请输入答题选项A  B  C  D');
            }
            if (empty($data['answer'])) {
                $this->error('请选择个正确答案');
            }
            if (empty($data['one_money'])) {
                $this->error('每个红包发放金额不能为空', null, null, 1);
            }
            if (empty($data['type'])) {
                $this->error('请选择发放类型', null, null, 1);
            }
            if (empty($data['createnum'])) {
                $this->error('红包数量不能为空', null, null, 1);
            }
            if (empty($data['address'])) {
                $data['receive_range'] = 0;
            }
            $answer=[
                'problem'=>$data['problem'],//问题
                'exact'=>$data['answer'],//答案
                'answer'=>[
                    'A'=>$data['A'],
                    'B'=>$data['B'],
                    'C'=>$data['C'],
                    'D'=>$data['D'],
                ]//选项
            ];
            $answer=json_encode($answer);
            if (empty($data['id'])) {
                $goods = [
                    'goods_name' => $data['goods_name'],
                    'goods_remark' => $data['goods_remark'],
                    'shop_price' => $data['shop_price'],
                    'original_img' => $data['original_img'],
                    'on_time' => time(),
                    'prom_type' => 6,
                    'store_count' => 9999,
                    'store_id' => STORE_ID,
                    'is_on_sale' => 1,
                    'goods_content' => $data['editor']
                ];
                $goods = M('goods')->add($goods);
                $packet = [
                    'store_id' => STORE_ID,
                    'goods_id' => $goods,
                    'status' => $data['status'],
                    'send_start_time' => $data['send_start_time'],
                    'send_end_time' => strtotime("+1 month"),
                    'name' => $data['goods_name'],
                    'type' => $data['type'],
                    'one_money' => $data['one_money'],
                    'all_money' => bcmul($data['createnum'], $data['one_money'], 2),
                    'createnum' => $data['createnum'],
                    'redpaket_info' => $data['redpaket_info'],
                    'percent' => $data['percent'],
                    'receive_range' => $data['receive_range'],
                    'address' => $data['address'],//经纬度
                    'answer' => $answer,//问题设置
                ];
                $row = M('red_packet')->add($packet);
            } else {
                $packet = [
                    'status' => $data['status'],
                    'send_start_time' => $data['send_start_time'],
                    'send_end_time' => strtotime("+1 month"),
                    'name' => $data['goods_name'],
                    'type' => $data['type'],
                    'one_money' => $data['one_money'],
                    'createnum' => $data['createnum'],
                    'redpaket_info' => $data['redpaket_info'],
                    'percent' => $data['percent'],
                    'receive_range' => $data['receive_range'],
                    'address' => $data['address'],//经纬度
                    'answer' => $answer,//问题设置
                ];
                $row = M('red_packet')->where(array('id' => $data['id'], 'store_id' => STORE_ID))->update($packet);
                $goodsId = M('red_packet')->where(array('id' => $data['id'], 'store_id' => STORE_ID))->value('goods_id');
                $goods = [
                    'goods_name' => $data['goods_name'],
                    'goods_remark' => $data['goods_remark'],
                    'shop_price' => $data['shop_price'],
                    'original_img' => $data['original_img'],
                    'last_update' => time(),
                    'goods_content' => $data['editor'],
                    'on_time' => time(),
                    'prom_type' => 6,
                ];
                $goods = M('goods')->where(array('goods_id' => $goodsId))->update($goods);
            }
            if (!$row || !$goods) {
                Db::rollback();
                $this->error('添加 / 编辑红包失败');
            }
            Db::commit();
            $this->success('添加 / 编辑红包成功', U('Redpacket/index'));
            exit;
        }
        $cid = I('get.id/d');
        if ($cid) {
            $redPacket = M('red_packet')->where(array('id' => $cid, 'store_id' => STORE_ID))->find();
            if (empty($redPacket)) {
                $this->error('红包不存在');
            }
            $goods = M('goods')->where(array('goods_id' => $redPacket['goods_id'], 'store_id' => STORE_ID))->field('goods_name,goods_remark,shop_price,original_img,goods_content')->find();
            $store = M('store')->where(array('store_id' => STORE_ID))->field('province_id,city_id,district,store_address')->find();
            $goods['store_address'] = $store['store_address'];
            $redPacket['answer']=json_decode($redPacket['answer'],true);
            $this->assign('goodsInfo', $goods);
            $this->assign('redpacket', $redPacket);
        } else {
            $def['send_start_time'] = time();
            $def['send_end_time'] = strtotime("+1 month");
            $store = M('store')->where(array('store_id' => STORE_ID))->field('province_id,city_id,district,store_address')->find();
            $this->assign('goodsInfo', $store);
            $this->assign('redpacket', $def);
        }
        return $this->fetch();
    }


    /*
     *红包发放
     */
    public function all_redpacket()
    {
        $cid = I('cid/d');
        $redPacket = M('red_packet')->where(array('id' => $cid, 'store_id' => STORE_ID))->find();
        $goods = M('goods')->where(array('goods_id' => $redPacket['goods_id']))->field('goods_name,goods_remark,shop_price,original_img')->find();
        //计算扣除平台费之后能发多少红包
        $platformFee = M('business_ad_bill')->where(array('id' => 1))->value('platform_fee');
        //红包总价 = 数量 * 单个价格
        $numMie = bcmul($redPacket['one_money'], $redPacket['createnum'], 2);
        //服务费 = 红包总价 * 服务费（25%）
        $money = bcmul($numMie, ($platformFee / 100), 2);
        //需要支付 = 红包总价 + 服务费
        $moneyAll = bcadd($numMie, $money, 2);

        //生成红包记录
        $orderSn = date('Ymd') . str_pad(mt_rand(1, 99999), 5, '0', STR_PAD_LEFT);
        $release = [
            'store_id' => $redPacket['store_id'],
            'order_sn' => $orderSn,
            'redpacket_id' => $redPacket['id'],
            'one_money' => $redPacket['one_money'],
            'cost' => $money,
            'all_money' => $moneyAll,
            'start' => 0,
            'num' => $redPacket['createnum'],
            'remark' => '红包个数:' . $redPacket['createnum'] . ' , 单个红包价格:' . $redPacket['one_money'] . '(元) , 服务费收取:' . $platformFee . '%  , 支付:' . $moneyAll . ' (元)',
        ];
        $releases=M('red_packet_release_log')->where(array('store_id' => $redPacket['store_id'], 'redpacket_id' => $redPacket['id']))->find();
        if (!count($releases)) {
            M('red_packet_release_log')->add($release);
        } else {
            if (empty($releases['start'])){
                M('red_packet_release_log')->where(array('store_id' => $redPacket['store_id'], 'redpacket_id' => $redPacket['id']))->save($release);
            }
        }

        //easywechat 实例化  扫码支付
        $app = new Application(C('options'));
        $attributes = [
            'trade_type' => 'NATIVE', // JSAPI，NATIVE，APP...
            'body' => $redPacket['name'],
            'detail' => '这里是detail，可选',
            'out_trade_no' => $orderSn,
            'total_fee' => bcmul($moneyAll,100), // 单位：分// 支付结果通知网址，如果不设置则会使用配置里的默认地址
            'notify_url' => 'http://skhcenter.baoliy168.com/index.php/seller/Wexin/weixin_callback',
        ];
        //初始化订单
        $order = new Order($attributes);
        $payment = $app->payment;
        $result = $payment->prepare($order);
        if ($result->return_code == 'SUCCESS' && $result->result_code == 'SUCCESS') {
            $prepayId = $result->prepay_id;
            $codeUrl = $result->code_url;
            $this->assign('code_str', $codeUrl);
        }
        $this->assign('moneyall', $moneyAll);//平台
        $this->assign('money', $money);//平台
        $this->assign('platformfee', $platformFee);//平台
        $this->assign('goods', $goods);// 赋值
        $this->assign('redpacket', $redPacket);// 赋值
        return $this->fetch();
    }

    //红包详情
    public function packet_list()
    {
//        $list = Db::name('red_packet')
//            ->alias('p')
//            ->field('p.goods_id,p.send_start_time,g.goods_name,g.original_img,g.shop_price,g.goods_remark,g.last_update,g.sales_sum,s.store_address')
//            ->join("goods g", "g.goods_id = p.goods_id", "INNER")
//            ->join("store s", "s.store_id = p.store_id", "LEFT")
//            ->where(['p.pay_status' => 1, 'status' => 1, 'type' => 1])
//            ->page($p, 10)
//            ->select();
        $id = I('get.id/d');
        $count = M('red_packet_log')->where('redpacket_id', $id)->count();
        $Page = new Page($count, 15);
        $show = $Page->show();
        $list = M('red_packet_log')->where('redpacket_id', $id)
            ->order('start_time asc')
            ->limit($Page->firstRow . ',' . $Page->listRows)->select();
        foreach ($list as $k => $v) {
            $list[$k]['user_name'] = $this->getUserName($v['user_id']);
            $list[$k]['share_man_name'] = $this->getUserName($v['share_man_id']);
        }
        $this->assign('page', $show);// 赋值分页输出
        $this->assign('lists', $list);
        return $this->fetch();
    }

    //获取用户姓名
    public function getUserName($uid)
    {
        return M('users')->where('user_id', $uid)->value('nickname');
    }
    
    public function pay_status()
    {
        $store_id = I('store_id/d');
        $redpacket_id = I('redpacket_id/d');
        $redPacket = M('red_packet')->where(array('id' => $redpacket_id, 'store_id' => $store_id))->field('pay_status')->find();
        exit(json_encode($redPacket));
    }

    //编辑器
    public function editor()
    {
        $action = I('action');
        switch ($action) {
            case 'config':
                $result =  json_encode($this->config);
                break;
            /* 上传图片 */
            case 'uploadimage':
                $image=uploadFile($_FILES['upfile']);
                if ($image){
                    $result=$this->ajaxReturn(array(
                        'state'=> 'SUCCESS',
                        'url'=>$image['data'],
                    ));
                }else{
                    $result=$this->ajaxReturn(array(
                        'state'=> '图片上传失败',
                    ));
                }
                break;
            case 'catchimage':
                $list = array();
                $fieldName = $this->config['catcherFieldName'];
                if (isset($_POST[$fieldName])) {
                    $source = $_POST[$fieldName];
                } else {
                    $source = $_GET[$fieldName];
                }
                foreach ($source as $imgUrl) {
                    array_push($list, array(
                        "state" => 'SUCCESS',
                        "url" => $imgUrl,
                    ));
                }
                /* 返回抓取数据 */
                $result= json_encode(array(
                    'state'=> count($list) ? 'SUCCESS':'ERROR',
                    'list'=> $list
                ));
                break;
                /* 上传涂鸦 */
            case 'uploadscrawl':
                /* 上传视频 */
            case 'uploadvideo':
                /* 上传文件 */
            case 'uploadfile':
                $result=json_encode(array(
                    'state'=> 'SUCCESS',
                    'url'=>'https://p0.meituan.net/dpmerchantpic/63f77834a5c367f68f2dea33d0ad0c352091291.jpg%40watermark%3D1%26%26r%3D1%26p%3D9%26x%3D2%26y%3D2%26relative%3D1%26o%3D20',
                ));
                break;
            default:
                $result = json_encode(array(
                    'state'=> '请求地址出错'
                ));
                break;
        }
        if (isset($_GET["callback"])) {
            if (preg_match("/^[\w_]+$/", $_GET["callback"])) {
                echo htmlspecialchars($_GET["callback"]) . '(' . $result . ')';
            } else {
                echo json_encode(array(
                    'state'=> 'callback参数不合法'
                ));
            }
        } else {
            echo $result;
        }
    }

}